language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t damiangasiorowski/docker-ci -f Dockerfile.dev .

script:
    - docker run -e CI=true damiangasiorowski/docker-ci npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-ci"
    env: "DockerCi-env"
    bucker_name: "elasticbeanstalk-us-east-2-102560297655"
    bucket_path: "docker-ci"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY