language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t damiangasiorowski/docker-ci -f Dockerfile.dev .

script:
    - docker run -e CI=true damiangasiorowski/docker-ci npm run test -- --coverage